# Plugin name
name: SpigotMaintenance
# Your main executable class (change package name to your package)
main: ch.tekk.spigotmaintenance.Main
# Plugin version
version: 1.0
api-version: 1.19
# Your name
author: Example
# Your website related to the plugin (optional)
website: https://example.org/
# Plugin description
description: A simple spigot plugin using maven.
# Available commands of your plugin
commands:
  maintenance:
    description: Check if the server is in maintenance
    usage: /<command>
    permission: spigotmaintenance.info
permissions:
  spigotmaintenance.*:
    description: Gives access to all commands of your plugin
    children:
      spigotmaintenance.info:
        description: Check if the server is in maintenance mode
        default: op
      spigotmaintenance.enable:
        description: Allows enabling of maintenance mode
        default: op
      spigotmaintenance.disable:
        description: Allows disabling of maintenance mode
        default: op
      spigotmaintenance.bypass:
        description: Bypasses maintenance mode
        default: op